//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chinczyk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_pl_PL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_pl_PL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chinczyk.Language-pl-PL", typeof(Language_pl_PL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę NIEBIESKIEGO gracza.
        /// </summary>
        internal static string pBlueName {
            get {
                return ResourceManager.GetString("pBlueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIEBIESKI.
        /// </summary>
        internal static string pCheckBoxB {
            get {
                return ResourceManager.GetString("pCheckBoxB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIELONY.
        /// </summary>
        internal static string pCheckBoxG {
            get {
                return ResourceManager.GetString("pCheckBoxG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZERWONY.
        /// </summary>
        internal static string pCheckBoxR {
            get {
                return ResourceManager.GetString("pCheckBoxR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŻÓŁTY.
        /// </summary>
        internal static string pCheckBoxY {
            get {
                return ResourceManager.GetString("pCheckBoxY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chińczyk.
        /// </summary>
        internal static string pFormName {
            get {
                return ResourceManager.GetString("pFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROZPOCZNIJ GRĘ.
        /// </summary>
        internal static string pGameStart {
            get {
                return ResourceManager.GetString("pGameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę ZIELONEGO gracza.
        /// </summary>
        internal static string pGreenName {
            get {
                return ResourceManager.GetString("pGreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalna liczba graczy wynosi 2.
        /// </summary>
        internal static string pMinPlayers {
            get {
                return ResourceManager.GetString("pMinPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę CZERWONEGO gracza .
        /// </summary>
        internal static string pRedName {
            get {
                return ResourceManager.GetString("pRedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę ŻÓŁTEGO gracza .
        /// </summary>
        internal static string pYellowName {
            get {
                return ResourceManager.GetString("pYellowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tura następnego gracza.
        /// </summary>
        internal static string tTolTipB {
            get {
                return ResourceManager.GetString("tTolTipB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tura gracza CZERWONEGO.
        /// </summary>
        internal static string tTolTipL0 {
            get {
                return ResourceManager.GetString("tTolTipL0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tura gracza ŻÓŁTEGO.
        /// </summary>
        internal static string tTolTipL1 {
            get {
                return ResourceManager.GetString("tTolTipL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tura gracza NIEBIESKIEGO.
        /// </summary>
        internal static string tTolTipL2 {
            get {
                return ResourceManager.GetString("tTolTipL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tura gracza ZIELONEGO.
        /// </summary>
        internal static string tTolTipL3 {
            get {
                return ResourceManager.GetString("tTolTipL3", resourceCulture);
            }
        }
    }
}
